In [1]:
# Import NumPy
import numpy as np

In [4]:
# Checking NumPy Version
print(np.__version__)

1.21.5


In [5]:
# Creating a NumPy array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [7]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
# Use a tuple to create a NumPy array
import numpy as np 
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


## Task 1

In [10]:
# Import NumPy
import numpy as np
# Checking NumPy Version
print(np.__version__)

1.21.5


In [11]:
# Creating a NumPy array
arr = np.array(["Valent","Aderiandra","https://www.linkedin.com/in/valentaderiandra/"])
print(arr)

['Valent' 'Aderiandra' 'https://www.linkedin.com/in/valentaderiandra/']


In [12]:
# Use a tuple to create a NumPy array
import numpy as np 
arr = np.array(("Valent","Aderiandra","https://www.linkedin.com/in/valentaderiandra/"))
print(arr)

['Valent' 'Aderiandra' 'https://www.linkedin.com/in/valentaderiandra/']


# Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

## 0 Dimensional Array

In [5]:
import numpy as np

arr = np.array(1)
print (arr)

1


## 1 Dimensional Array

In [10]:
import numpy as np

arr = np.array([1])
print (arr)

[1]


## 2 Dimensional Array with 2 1 dimensional array

In [8]:
import numpy as np

arr = np.array([[1],[2]])
print (arr)

[[1]
 [2]]


## 3D array with 2 2D array

In [9]:
import numpy as np

arr = np.array([[[1],[2]],[[3],[4]]])
print (arr)

[[[1]
  [2]]

 [[3]
  [4]]]


## Task 2

In [13]:
# 1 D
import numpy as np
arr = np.array(["Valent","Aderiandra"])
print(arr)

['Valent' 'Aderiandra']


In [14]:
# 2 Dimensions with 2 arrays
import numpy as np
arr = np.array([["Valent","Aderiandra"],["https://www.linkedin.com/in/valentaderiandra/","https://github.com/valentaderiandra"]])
print(arr)


[['Valent' 'Aderiandra']
 ['https://www.linkedin.com/in/valentaderiandra/'
  'https://github.com/valentaderiandra']]


In [21]:
# 3 D
import numpy as np
arr2 = np.array([
    [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
 [[1, 0, 0], [1, 1, 0], [1, 1, 1]],
 [[1, 0, 0], [0, 0, 0], [0, 0, 1]]
])
print(arr2)

[[[1 0 0]
  [0 1 0]
  [0 0 1]]

 [[1 0 0]
  [1 1 0]
  [1 1 1]]

 [[1 0 0]
  [0 0 0]
  [0 0 1]]]


# Check the array dimensions

In [13]:
import numpy as np

dimensions0 = np.array(1)
dimensions1 = np.array([1])
dimensions2 = np.array([[1],[2]])
dimensions3 = np.array([[[1],[2]],[[3],[4]]])

print(dimensions0.ndim)
print(dimensions1.ndim)
print(dimensions2.ndim)
print(dimensions3.ndim)

0
1
2
3


## Task 3

In [14]:
# Check how many dimensions the arrays have
import numpy as np 

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
d = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Create a 5-dimensional array and try to check whether the array is a 5-dimensional array

In [1]:
# np.array(x), if x is more than 5 dimensions then the ndmin command will not work so for example x is made a 7-dimensional array then the output is a 7-dimensional array
import numpy as np

arr = np.array([[1,2,3,4,5]],ndmin=5)
print(arr)
print('Number of dimensions :',arr.ndim)

[[[[[1 2 3 4 5]]]]]
Number of dimensions : 5


In [2]:
# Find the first element of the array
import numpy as np

arr = np.array([1,2,3,4,5])
print (arr[0])

1


In [27]:
# Find the second element of the array
import numpy as np

arr = np.array([1,2,3,4,5])
print (arr[1])

2


In [29]:
# Find the second and third elements of the array, then add them up
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[1]+arr[2])

5


# Task 4


In [34]:
import random 
import numpy as np
#Generate 5 random numbers between 10 and 30
randomlist = random.sample(range(10, 30), 10)
print(randomlist)

print(randomlist[0:3])
print(randomlist[0:3:2])

[10, 17, 13, 12, 26, 19, 25, 21, 29, 27]
[10, 17, 13]
[10, 13]


# Find elements from array

In [31]:
# Find elements of the first array, second row
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row :', arr[0,1])

2nd element on 1st row : 2


In [33]:
# Find element from 2nd row,5th column
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd row :', arr[1,4])

5th element on 2nd row : 10


In [34]:
# Acces the third element of the second array of the first array
import numpy as np

arr = np.array([
[[1,2,3],[4,5,6]],
[[7,8,9],[10,11,12]]
])
print(arr[0,1,2])

6


In [36]:
# print the Last element from the 2nd array
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from 2nd dim : ',arr[1,-1])

Last element from 2nd dim :  10


In [3]:
# Slice elements from index 1st to index 3rd from the first array
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Elements that are in the first index to the third index of the first array : ',arr[0,1:4])

Elements that are in the first index to the third index of the first array :  [2 3 4]


In [40]:
# Slice elements from index 4 to the end of the array 

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[4:])

[ 5  6  7  8  9 10]


In [41]:
# Slice elements from beginning to the index 4 (not included)

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[:4])

[1 2 3 4]


In [42]:
# Slice elements from the index 3 from the end of to index 1 from the end 
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[-3:-1])

[8 9]


In [45]:
# Show even numbers from the array below
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1: :2])
print(arr[1, : :2])

[2 4]
[ 6  8 10]


In [47]:
# Show 3 numbers from index 0 of each array
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:,:3])

[[1 2 3]
 [6 7 8]]


# Task 5

In [4]:
# Acces the element on the first row,second coloumn
import numpy as np 

arr = np.array([1,2,3,4,5])
print("From list {} the answer for arr[1] is".format(arr),arr[1])

From list [1 2 3 4 5] the answer for arr[1] is 2


In [5]:
import numpy as np 

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("From list {} the answer for arr[1,3] is".format(arr),arr[1,3])

From list [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] the answer for arr[1,3] is 9


In [6]:
import numpy as np 

arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print("From list {} the answer for arr[1,1,2] is".format(arr),arr[1,1,2])

From list [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]] the answer for arr[1,1,2] is 18
